{
  "uid" : "b3210fb3418e170b",
  "name" : "test_user_add",
  "fullName" : "test_case.test_002_user_add.Test_User_add#test_user_add",
  "historyId" : "84039d43224d4034e83312c8ca354a99",
  "time" : {
    "start" : 1663252487314,
    "stop" : 1663252502685,
    "duration" : 15371
  },
  "description" : "正常添加用户",
  "descriptionHtml" : "<p>正常添加用户</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 7,
  "retriesStatusChange" : true,
  "beforeStages" : [ {
    "name" : "_xunit_setup_class_fixture_Test_User_add",
    "time" : {
      "start" : 1663252487313,
      "stop" : 1663252487314,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "testStage" : {
    "description" : "正常添加用户",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "2d793772f94e3a4a",
      "name" : "log",
      "source" : "2d793772f94e3a4a.txt",
      "type" : "text/plain",
      "size" : 69
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : false
  },
  "afterStages" : [ {
    "name" : "_xunit_setup_class_fixture_Test_User_add::0",
    "time" : {
      "start" : 1663252502685,
      "stop" : 1663252507838,
      "duration" : 5153
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "labels" : [ {
    "name" : "story",
    "value" : "正常添加用户"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "suite",
    "value" : "用户列表添加用户测试用例"
  }, {
    "name" : "parentSuite",
    "value" : "test_case"
  }, {
    "name" : "subSuite",
    "value" : "Test_User_add"
  }, {
    "name" : "host",
    "value" : "PC-201903070025"
  }, {
    "name" : "thread",
    "value" : "6288-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_case.test_002_user_add"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "34c27517b702648f",
      "status" : "passed",
      "time" : {
        "start" : 1663252354763,
        "stop" : 1663252370038,
        "duration" : 15275
      }
    }, {
      "uid" : "fe2c0e7ffcae56e8",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@placeholder=\"请输入用户名\"]\"}\n  (Session info: chrome=105.0.5195.102)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x005DAF23+2207523]\n\tOrdinal0 [0x005730E1+1781985]\n\tOrdinal0 [0x00483FE8+802792]\n\tOrdinal0 [0x004B2290+991888]\n\tOrdinal0 [0x004B252B+992555]\n\tOrdinal0 [0x004DF6E2+1177314]\n\tOrdinal0 [0x004CD634+1103412]\n\tOrdinal0 [0x004DD9F2+1169906]\n\tOrdinal0 [0x004CD406+1102854]\n\tOrdinal0 [0x004A75F0+947696]\n\tOrdinal0 [0x004A84E6+951526]\n\tGetHandleVerifier [0x00882A12+2733954]\n\tGetHandleVerifier [0x00874E28+2677656]\n\tGetHandleVerifier [0x006646EA+513114]\n\tGetHandleVerifier [0x00663796+509190]\n\tOrdinal0 [0x00579CEB+1809643]\n\tOrdinal0 [0x0057E448+1827912]\n\tOrdinal0 [0x0057E535+1828149]\n\tOrdinal0 [0x00587960+1866080]\n\tBaseThreadInitThunk [0x755D343D+18]\n\tRtlInitializeExceptionChain [0x77619812+99]\n\tRtlInitializeExceptionChain [0x776197E5+54]",
      "time" : {
        "start" : 1663252271936,
        "stop" : 1663252271936,
        "duration" : 0
      }
    }, {
      "uid" : "e5b9b63cf6f7616f",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=55684): Max retries exceeded with url: /session/8a924fc9915aabea005751656e2f9571/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000391BA30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1663251481287,
        "stop" : 1663251481287,
        "duration" : 0
      }
    }, {
      "uid" : "959b83d44b9663d1",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54819): Max retries exceeded with url: /session/de5bf17edac7f96798f1bcc891a1b88f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003878B20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1663214222339,
        "stop" : 1663214222339,
        "duration" : 0
      }
    }, {
      "uid" : "3ffb4989370f6883",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@placeholder=\"请输入用户名\"]\"}\n  (Session info: chrome=105.0.5195.102)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x005DAF23+2207523]\n\tOrdinal0 [0x005730E1+1781985]\n\tOrdinal0 [0x00483FE8+802792]\n\tOrdinal0 [0x004B2290+991888]\n\tOrdinal0 [0x004B252B+992555]\n\tOrdinal0 [0x004DF6E2+1177314]\n\tOrdinal0 [0x004CD634+1103412]\n\tOrdinal0 [0x004DD9F2+1169906]\n\tOrdinal0 [0x004CD406+1102854]\n\tOrdinal0 [0x004A75F0+947696]\n\tOrdinal0 [0x004A84E6+951526]\n\tGetHandleVerifier [0x00882A12+2733954]\n\tGetHandleVerifier [0x00874E28+2677656]\n\tGetHandleVerifier [0x006646EA+513114]\n\tGetHandleVerifier [0x00663796+509190]\n\tOrdinal0 [0x00579CEB+1809643]\n\tOrdinal0 [0x0057E448+1827912]\n\tOrdinal0 [0x0057E535+1828149]\n\tOrdinal0 [0x00587960+1866080]\n\tBaseThreadInitThunk [0x755D343D+18]\n\tRtlInitializeExceptionChain [0x77619812+99]\n\tRtlInitializeExceptionChain [0x776197E5+54]",
      "time" : {
        "start" : 1663213543413,
        "stop" : 1663213543413,
        "duration" : 0
      }
    }, {
      "uid" : "1b9ac1210b4906b8",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54575): Max retries exceeded with url: /session/64446d677d899cf2c750cad742d941db/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003855B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1663213050229,
        "stop" : 1663213050229,
        "duration" : 0
      }
    }, {
      "uid" : "5bbec36a20d9e1fe",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54458): Max retries exceeded with url: /session/a58ba9bcffc1e4a3746c07fa46e41b47/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003853A60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1663211570381,
        "stop" : 1663211570381,
        "duration" : 0
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "b3210fb3418e170b.json",
  "parameterValues" : [ ]
}