{"name": "test_user_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert '添加用户成功' == <selenium.webdriver.remote.webelement.WebElement (session=\"e90251e63e7f97867f963a012a225489\", element=\"a3ebe7a9-ad58-4af1-bbce-74a6935c16be\")>", "trace": "self = <test_case.test_002_user_add.Test_User_add object at 0x0000000003B47F10>\n\n    @allure.story(\"正常添加用户\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_user_add(self):\n        \"\"\"正常添加用户\"\"\"\n        Logger().info(\"user add success\")\n        try:\n            self.user_add.user_add(username, password, email)\n        except NoSuchElementException:\n            Logger().error(\"user_add no find element\")\n        text = User_Add_Page_Locator().user_add_succee()\n        print(text)\n>       assert \"添加用户成功\" == text\nE       assert '添加用户成功' == <selenium.webdriver.remote.webelement.WebElement (session=\"e90251e63e7f97867f963a012a225489\", element=\"a3ebe7a9-ad58-4af1-bbce-74a6935c16be\")>\n\ntest_case\\test_002_user_add.py:43: AssertionError"}, "description": "正常添加用户", "attachments": [{"name": "log", "source": "563c264a-e7bb-4ed6-a55f-e24755ba4d0f-attachment.txt", "type": "text/plain"}], "start": 1663637659624, "stop": 1663637674851, "uuid": "2dbac676-b0fe-4c58-a8da-c8f2d710446e", "historyId": "84039d43224d4034e83312c8ca354a99", "testCaseId": "36b76c837d963a84b27ec03de67a9f4c", "fullName": "test_case.test_002_user_add.Test_User_add#test_user_add", "labels": [{"name": "story", "value": "正常添加用户"}, {"name": "suite", "value": "用户列表添加用户测试用例"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "test_case"}, {"name": "subSuite", "value": "Test_User_add"}, {"name": "host", "value": "PC-201903070025"}, {"name": "thread", "value": "4880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_002_user_add"}]}