{"name": "test_user_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert '添加用户成功' == <selenium.webdriver.remote.webelement.WebElement (session=\"69748fe9d2ddd33955bd7dacae561f74\", element=\"fb3b6d75-c3ce-468d-b062-615a48c6e24c\")>", "trace": "self = <test_case.test_002_user_add.Test_User_add object at 0x00000000039D7EB0>\n\n    @allure.story(\"正常添加用户\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_user_add(self):\n        \"\"\"正常添加用户\"\"\"\n        Logger().info(\"user add success\")\n        try:\n            self.user_add.user_add(username, password, email)\n        except NoSuchElementException:\n            Logger().error(\"user_add no find element\")\n        text = User_Add_Page_Locator().user_add_succee()\n>       assert \"添加用户成功\" == text\nE       assert '添加用户成功' == <selenium.webdriver.remote.webelement.WebElement (session=\"69748fe9d2ddd33955bd7dacae561f74\", element=\"fb3b6d75-c3ce-468d-b062-615a48c6e24c\")>\n\ntest_case\\test_002_user_add.py:42: AssertionError"}, "description": "正常添加用户", "attachments": [{"name": "log", "source": "f37120dc-4d61-4053-b626-d3d5e39156da-attachment.txt", "type": "text/plain"}], "start": 1663636578106, "stop": 1663636593399, "uuid": "85ca344c-86cb-44a7-ac19-668d586c49b7", "historyId": "84039d43224d4034e83312c8ca354a99", "testCaseId": "36b76c837d963a84b27ec03de67a9f4c", "fullName": "test_case.test_002_user_add.Test_User_add#test_user_add", "labels": [{"name": "suite", "value": "用户列表添加用户测试用例"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "正常添加用户"}, {"name": "parentSuite", "value": "test_case"}, {"name": "subSuite", "value": "Test_User_add"}, {"name": "host", "value": "PC-201903070025"}, {"name": "thread", "value": "5692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_002_user_add"}]}